### ISSUE TITLE
run stage1 meet error

### ISSUE THREAD

**Issue by echohux** [shanemankiw/SO-SMPL#11]
run:bash scripts/stage1/public_loop_m.sh
get error:
Traceback (most recent call last):
  File "/hdd/hyy/SO-SMPL/launch.py", line 202, in <module>
    main()
  File "/hdd/hyy/SO-SMPL/launch.py", line 116, in main
    system: BaseSystem = threestudio.find(cfg.system_type)(
  File "/hdd/hyy/SO-SMPL/threestudio/systems/base.py", line 41, in __init__
    self.configure()
  File "/hdd/hyy/SO-SMPL/threestudio/systems/smpl_human.py", line 39, in configure
    self.guidance = threestudio.find(self.cfg.guidance_type)(self.cfg.guidance)
  File "/hdd/hyy/SO-SMPL/threestudio/utils/base.py", line 88, in __init__
    self.configure(*args, **kwargs)
  File "/hdd/hyy/SO-SMPL/threestudio/models/guidance/controlnet_vsd_guidance_smpl.py", line 190, in configure
    lora_attn_procs[name] = LoRAAttnProcessor(
TypeError: __init__() got an unexpected keyword argument 'hidden_size'
and
Traceback (most recent call last):
  File "/hdd/hyy/SO-SMPL/launch.py", line 202, in <module>
    main()
  File "/hdd/hyy/SO-SMPL/launch.py", line 116, in main
    system: BaseSystem = threestudio.find(cfg.system_type)(
  File "/hdd/hyy/SO-SMPL/threestudio/systems/base.py", line 41, in __init__
    self.configure()
  File "/hdd/hyy/SO-SMPL/threestudio/systems/smpl_human.py", line 39, in configure
    self.guidance = threestudio.find(self.cfg.guidance_type)(self.cfg.guidance)
  File "/hdd/hyy/SO-SMPL/threestudio/utils/base.py", line 88, in __init__
    self.configure(*args, **kwargs)
  File "/hdd/hyy/SO-SMPL/threestudio/models/guidance/controlnet_vsd_guidance_smpl.py", line 175, in configure
    self.unet_lora.set_attn_processor(lora_attn_procs)
  File "/root/miniconda3/envs/sosmpl/lib/python3.9/site-packages/diffusers/models/unets/unet_2d_condition.py", line 738, in set_attn_processor
    raise ValueError(
ValueError: A dict of processors was passed, but the number of processors 0 does not match the number of attention layers: 32. Please make sure to pass 32 processor classes.

**Comment by shanemankiw** [comment]
Hi, sorry for the late reply. This isn't really something I have encountered. But it seems like the error is about the LoRAAttnProcessor? Could you provide the version of your diffusers? Maybe the LoRAAttnProcessor is updated in newer versions and is no longer applicable.
