### ISSUE TITLE
run stage1 meet

### ISSUE THREAD

**Issue by XiaokunSun** [shanemankiw/SO-SMPL#9]
run:`bash scripts/stage1/public_loop_m.sh`
get error:
```
Traceback (most recent call last):
  File "launch.py", line 203, in <module>
    main()
  File "launch.py", line 90, in main
    import threestudio
  File "/data1/SunXiaoKun/Project/SO-SMPL/threestudio/__init__.py", line 36, in <module>
    from . import data, models, systems
  File "/data1/SunXiaoKun/Project/SO-SMPL/threestudio/models/__init__.py", line 1, in <module>
    from . import (
  File "/data1/SunXiaoKun/Project/SO-SMPL/threestudio/models/guidance/__init__.py", line 1, in <module>
    from . import (
  File "/data1/SunXiaoKun/Project/SO-SMPL/threestudio/models/guidance/controlnet_guidance.py", line 13, in <module>
    from threestudio.models.prompt_processors.base import PromptProcessorOutput
  File "/data1/SunXiaoKun/Project/SO-SMPL/threestudio/models/prompt_processors/__init__.py", line 1, in <module>
    from . import (
  File "/data1/SunXiaoKun/Project/SO-SMPL/threestudio/models/prompt_processors/base_clothes.py", line 38, in <module>
    class SemanticConfig:
  File "/data1/SunXiaoKun/Project/SO-SMPL/threestudio/models/prompt_processors/base_clothes.py", line 42, in SemanticConfig
    condition: Callable[
  File "/data1/SunXiaoKun/Others/Software/anaconda3/envs/cd117py38tc200_barbie/lib/python3.8/typing.py", line 816, in __getitem__
    return self.__getitem_inner__(params)
  File "/data1/SunXiaoKun/Others/Software/anaconda3/envs/cd117py38tc200_barbie/lib/python3.8/typing.py", line 261, in inner
    return func(*args, **kwds)
  File "/data1/SunXiaoKun/Others/Software/anaconda3/envs/cd117py38tc200_barbie/lib/python3.8/typing.py", line 839, in __getitem_inner__
    args = tuple(_type_check(arg, msg) for arg in args)
  File "/data1/SunXiaoKun/Others/Software/anaconda3/envs/cd117py38tc200_barbie/lib/python3.8/typing.py", line 839, in <genexpr>
    args = tuple(_type_check(arg, msg) for arg in args)
  File "/data1/SunXiaoKun/Others/Software/anaconda3/envs/cd117py38tc200_barbie/lib/python3.8/typing.py", line 149, in _type_check
    raise TypeError(f"{msg} Got {arg!r:.100}.")
TypeError: Callable[[arg, ...], result]: each arg must be a type. Got [<class 'str'>].
Traceback (most recent call last):
  File "launch.py", line 203, in <module>
    main()
  File "launch.py", line 90, in main
    import threestudio
  File "/data1/SunXiaoKun/Project/SO-SMPL/threestudio/__init__.py", line 36, in <module>
    from . import data, models, systems
  File "/data1/SunXiaoKun/Project/SO-SMPL/threestudio/models/__init__.py", line 1, in <module>
    from . import (
  File "/data1/SunXiaoKun/Project/SO-SMPL/threestudio/models/guidance/__init__.py", line 1, in <module>
    from . import (
  File "/data1/SunXiaoKun/Project/SO-SMPL/threestudio/models/guidance/controlnet_guidance.py", line 13, in <module>
    from threestudio.models.prompt_processors.base import PromptProcessorOutput
  File "/data1/SunXiaoKun/Project/SO-SMPL/threestudio/models/prompt_processors/__init__.py", line 1, in <module>
    from . import (
  File "/data1/SunXiaoKun/Project/SO-SMPL/threestudio/models/prompt_processors/base_clothes.py", line 38, in <module>
    class SemanticConfig:
  File "/data1/SunXiaoKun/Project/SO-SMPL/threestudio/models/prompt_processors/base_clothes.py", line 42, in SemanticConfig
    condition: Callable[
  File "/data1/SunXiaoKun/Others/Software/anaconda3/envs/cd117py38tc200_barbie/lib/python3.8/typing.py", line 816, in __getitem__
    return self.__getitem_inner__(params)
  File "/data1/SunXiaoKun/Others/Software/anaconda3/envs/cd117py38tc200_barbie/lib/python3.8/typing.py", line 261, in inner
    return func(*args, **kwds)
  File "/data1/SunXiaoKun/Others/Software/anaconda3/envs/cd117py38tc200_barbie/lib/python3.8/typing.py", line 839, in __getitem_inner__
    args = tuple(_type_check(arg, msg) for arg in args)
  File "/data1/SunXiaoKun/Others/Software/anaconda3/envs/cd117py38tc200_barbie/lib/python3.8/typing.py", line 839, in <genexpr>
    args = tuple(_type_check(arg, msg) for arg in args)
  File "/data1/SunXiaoKun/Others/Software/anaconda3/envs/cd117py38tc200_barbie/lib/python3.8/typing.py", line 149, in _type_check
    raise TypeError(f"{msg} Got {arg!r:.100}.")
TypeError: Callable[[arg, ...], result]: each arg must be a type. Got [<class 'str'>].
```

**Comment by XiaokunSun** [comment]
my env: cuda11.7+py3.8+torch2.0.0, and I can run threestuio, so that's why?

**Comment by XiaokunSun** [comment]
Dear author, can you release the complete clean code?

**Comment by sunshineatnoon** [comment]
Same here

**Comment by sunshineatnoon** [comment]
I also got this error:
```
ImportError: cannot import name 'gan_volume_renderer' from partially initialized module
'threestudio.models.renderers' (most likely due to a circular import)
(SO-SMPL/threestudio/models/renderers/__init__.py)
```

**Comment by shanemankiw** [comment]
Hi, sorry for the late reply, I totally missed these issues...
The problem you mentioned is because of uncleaned, unnecessary imports. I cleaned up some code a while ago, and it should now work. If you still encounter any problem, please inform me.

Thank you!
